"""somechange

Revision ID: b89c05d45c49
Revises: 5add6ed658c5
Create Date: 2022-12-17 14:00:35.846021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89c05d45c49'
down_revision = '5add6ed658c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('order_items',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('order_items',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
