"""empty message

Revision ID: d6d577647907
Revises: b89c05d45c49
Create Date: 2022-12-17 16:51:49.588043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d577647907'
down_revision = 'b89c05d45c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_order')
    op.drop_table('_alembic_tmp_customer_order')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    op.create_table('_alembic_tmp_customer_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('order_items', sa.TEXT(), nullable=False),
    sa.Column('order_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice')
    )
    op.create_table('customer_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('order_items', sa.TEXT(), nullable=True),
    sa.Column('order_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice')
    )
    # ### end Alembic commands ###
