"""some907

Revision ID: eeaf520961e9
Revises: 09271448b944
Create Date: 2022-12-19 21:20:50.231133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeaf520961e9'
down_revision = '09271448b944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('carts_id', sa.Integer(), nullable=False))
        batch_op.alter_column('ordered_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key(None, 'cart', ['carts_id'], ['id'])
        batch_op.drop_column('deliver_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deliver_date', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ordered_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('carts_id')
        batch_op.drop_column('status')
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###
